---
title: "experimentos_divida"
output: 
  html_document:
    theme: cosmo
    code_folding: hide
    toc: yes
    toc_float: yes
  runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```

Pacotes.

```{r pacotes}
library(ckanr)
library(readxl)
library(readr)
library(tidyverse)
library(stringr)
library(viridis)
library(extrafont)
library(purrr)
library(plotly)
library(shiny)
# loadfonts()
# extrafont::font_import()

tema <- function(){
    theme_minimal() +
    theme(
      text = element_text(family = "Calibri Light", colour = "grey20"),
      title = element_text(face = "bold", size = 10, color = "#1E4C7A"), 
      plot.subtitle = element_text(family = "Calibri Light", 
                                   color = "grey20", face = "plain", size = 10),
      axis.text = element_text(family = "Calibri Light", colour = "grey20", size = 8),
      plot.caption = element_text(face = "italic"),
      panel.grid.major = element_blank(), 
      panel.grid.minor = element_blank(),
      legend.text = element_text(size = 14),
      legend.title = element_text(size = 14),
      axis.ticks = element_line(size = 0.5),
      axis.ticks.length = unit(.25, "cm"),
      axis.title = element_text(size = 8, colour = "grey20"),
      legend.position = 'none')
}

    # theme(legend.position = 'none',
    #     panel.grid.major.y = element_blank(),
    #     panel.grid.major.x = element_blank(),
    #     axis.title.y = element_blank(),
    #     axis.text.y = element_blank(),
    #     axis.ticks.y = element_blank(),
    #     plot.background = element_rect(color = "#f0f5f7", linetype = "solid", size = 2))
```

## Emissões e resgates

### Carga

```{r carga-dados, echo=FALSE}
### Leitura do Arquivo diretamente do ckan
tabela <- read_excel("Anexo_RMD_Dez_18.xlsx", skip = 4, sheet = "1.2")
```

Preparacao dos dados

```{r}

meses <- c("Jan", "Fev", "Mar", "Abr", "Mai", "Jun", "Jul", "Ago", "Set", "Out", "Nov", "Dez")

rotulos_nivel1 <- c("EMISSÕES",
                    "RESGATES")

rotulos_nivel2 <- c("DPMFi",
                    "DPFe")

dados <- tabela %>%
  rename(rotulos = 1) %>%
  filter(!is.na(rotulos)) %>%
  filter(!str_detect(rotulos, "Obs:"))

pos_nivel1 <- which(dados$rotulos %in% rotulos_nivel1)
pos_nivel2 <- which(dados$rotulos %in% rotulos_nivel2)

dados_2 <- dados %>%
  mutate(nivel1 = ifelse(row_number() %in% pos_nivel1,
                         rotulos,
                         NA),
         nivel2 = ifelse(row_number() %in% pos_nivel2,
                         rotulos,
                         NA)) %>%
  fill(nivel1) %>%
  fill(nivel2) %>%
  filter(!(rotulos %in% c(rotulos_nivel1, rotulos_nivel2))) %>%
  mutate(rotulos = ifelse(rotulos == "Prefixados", "Prefixado", rotulos)) %>%
  select(nivel1, nivel2, rotulos, everything())

dados_long <- dados_2 %>%
  gather(contains("/"), key = "Mes_Ano", value = "Valor") %>%
  separate(Mes_Ano, into = c("Mes", "Ano"), sep = "/") %>%
  mutate(Ano = paste0('20', Ano),
         Mes_num = match(Mes, meses),
         Periodo = as.Date(paste0(Ano, "-",
                                  str_pad(Mes_num, 2), "-",
                                  "01")))

dados_wide <- dados_long %>%
  spread(key = nivel1, value = Valor, fill = 0) %>%
  arrange(Periodo) %>%
  mutate(emissoes_liq = ifelse(`EMISSÕES`>`RESGATES`, `EMISSÕES` - `RESGATES`, 0),
         resgates_liq = ifelse(`EMISSÕES`>`RESGATES`, 0, `RESGATES` - `EMISSÕES`),
         liquido = `EMISSÕES` - `RESGATES`)

# this is beautiful!
teste <- dados_wide %>% 
  group_by(nivel2, rotulos, Ano) %>% 
  mutate_at(vars(`EMISSÕES`:liquido), .funs = funs(no_ano = cumsum(.))) %>%
  ungroup() %>%
  group_by(nivel2, rotulos) %>%
  mutate_at(vars(`EMISSÕES`:liquido), .funs = funs(ult_12 = zoo::rollapply(as.numeric(.), width = 12, FUN = sum, fill = NA, align = 'right')))

```
