---
title: "fatores de variação"
output: 
  flexdashboard::flex_dashboard:
    source_code: embed
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ckanr)
library(readxl)
library(readr)
library(tidyverse)
library(stringr)
library(viridis)
library(extrafont)
library(RColorBrewer)
library(purrr)
library(plotly)
library(shiny)
library(flexdashboard)
# loadfonts()
# extrafont::font_import()

tema <- function(){
    theme_minimal() +
    theme(
      text = element_text(family = "Source Sans Pro", colour = "grey20"),
      title = element_text(face = "bold", size = 10, color = "#1E4C7A"), 
      plot.subtitle = element_text(family = "Source Sans Pro", 
                                   color = "grey20", face = "plain", size = 10),
      axis.text = element_text(family = "Source Sans Pro", colour = "grey20", size = 8),
      plot.caption = element_text(face = "italic"),
      panel.grid.major = element_blank(), 
      panel.grid.minor = element_blank(),
      legend.text = element_text(size = 14),
      legend.title = element_text(size = 14),
      axis.ticks = element_line(size = 0.5),
      axis.ticks.length = unit(.25, "cm"),
      axis.title = element_text(size = 8, colour = "grey20"),
      legend.position = 'none')
}

vermelho <- brewer.pal(3, name = "Set1")[1]
azul <- "#1f476a" 

vermelho_claro <- "#ee7576"
azul_claro     <- "#2c90bf" # "#87b1d4"

```

```{r import-data, echo=FALSE}
### Leitura do Arquivo diretamente do ckan
tabela <- read_excel("Anexo_RMD_Dez_18.xlsx", skip = 4, sheet = "2.9")

linhas_de_interesse <- c("Estoque anterior1",
                         "Estoque mês em análise",
                         "Variação Nominal",
                         "I.1.1 - Emissões",
                         "I.1.2 - Resgates",
                         "I.2 - Juros  Apropriados",
                         "II.1 - Transferência de carteira 11")

lista_fatores <- c("Estoque_ant",
                   "Estoque_atu",
                   "Variacao",
                   "Emissoes",
                   "Resgates",
                   "Juros",
                   "Transf")

tab_novos_titulos <- tibble(linhas_de_interesse, lista_fatores)

meses <- c("Jan", "Fev", "Mar", "Abr", "Mai", "Jun", "Jul", "Ago", "Set", "Out", "Nov", "Dez")

colnames(tabela)[which(colnames(tabela) == "Out/16")+1] <- "Nov/16"
colnames(tabela)[which(colnames(tabela) == "Out/17")+1] <- "Nov/17"
# ^ por causa de um erro na planilha

dados <- tabela %>%
  filter(Indicadores %in% linhas_de_interesse) %>%
  left_join(tab_novos_titulos, by = c("Indicadores" = "linhas_de_interesse")) %>%
  select(-Indicadores) %>%
  select(fatores = lista_fatores, everything()) %>%
  gather(-fatores, key = mes_ano, value = valor) %>%
  filter(str_detect(mes_ano, "/")) %>%
  separate(mes_ano, into = c("Mes", "Ano"), sep = "/") %>%
  mutate(Ano = paste0('20', Ano),
         Mes_num = match(Mes, meses),
         Periodo = as.Date(paste0(Ano, "-",
                                  str_pad(Mes_num, 2), "-",
                                  "01")),
         valor = as.numeric(valor)) %>%
  spread(fatores, value = valor) %>%
  mutate(transf_positiva = ifelse(Transf > 0, Transf, 0),
         transf_negativa = ifelse(Transf > 0, 0,      Transf)) %>%
  select(-Transf, -Variacao) %>%
  gather(Emissoes:transf_negativa, key = "fatores", value = "valor")

### experimentos
# para gráfico de área
# Para poder fazer um gráfico de area, preciso segmentar o gráfico em grupo contíguos. Ou seja, agrupar as sequencias de negativos e positivos.

serie_variacao <- dados %>% 
  filter(fatores == "Variação") %>%
  mutate(resultado = ifelse(valor < 0, "Positivo", "Negativo"))

palavra_chave <- "Grupo_"
i <- 1
ultimo_grupo <- paste0("Grupo_", i)
grupo <- c(ultimo_grupo)

vetor <- serie_variacao$resultado

for (j in 2:length(vetor)) {
  if (vetor[j] != vetor[j-1]) {
    i <- i+1
    ultimo_grupo <- paste0("Grupo_", i)
  }
  grupo <- c(grupo, ultimo_grupo)
}

serie_variacao$grupos <- grupo

serie_variacao <- serie_variacao %>%
  mutate(var_acumulada = cumsum(valor))

polar <- ggplot(serie_variacao, 
                aes(x = Periodo, y = valor, fill = resultado, color = resultado, group = grupos)) +
  geom_area() +
  geom_line() +
  scale_color_manual(values = c("Positivo" = azul, "Negativo" = vermelho)) + 
  scale_fill_manual(values = c("Positivo" = azul_claro, "Negativo" = vermelho_claro)) + 
  coord_polar() + 
  scale_y_discrete(expand = expand_scale(add = c(-3e5,3e5))) + 
  tema()

polar2 <- ggplot(serie_variacao, 
                aes(x = Periodo, y = valor, fill = resultado)) +
  geom_col(color = NA) +
  scale_fill_manual(values = c("Positivo" = azul, "Negativo" = vermelho)) + 
  coord_polar() + 
  scale_y_discrete(expand = expand_scale(add = c(-3e5,3e5))) + 
  tema()

ggplot(dados, aes(y = fatores, x = Mes, fill = valor)) + geom_tile(color = "white") +
  scale_fill_viridis() + 
  coord_polar() +
  scale_y_discrete(expand = expand_scale(add = c(4,0))) +
  facet_wrap(~Ano) + tema() + theme(legend.position = "right")

### fim experimentos

# dados_graf <- dados %>%
#   spread(fatores, value = valor) %>%
#   mutate(Juros_x       = Estoque_ant,
#          Juros_xend    = Estoque_ant + Juros,
#          Emissoes_x    = Estoque_ant + Juros,
#          Emissoes_xend = Estoque_ant + Juros + `Emissões`,
#          Resgates_x    = Estoque_ant + Juros + `Emissões`,
#          Resgates_xend = Estoque_ant + Juros + `Emissões` + Resgates)
#   # tive uma ideia melhor...

unique(dados$fatores)

fatores_ordenados <- c("Estoque_ant", "Juros", "Emissoes", "transf_positiva", "transf_negativa", "Resgates")

dados_graf <- dados %>%
  filter(fatores %in% fatores_ordenados) %>%
  mutate(fatores = factor(fatores, levels = fatores_ordenados, ordered = TRUE)) %>%
  arrange(Periodo, fatores) %>%
  group_by(Periodo) %>%
  mutate(yend = cumsum(valor),
         y = lag(yend,1)) %>%
  ungroup() %>%
  mutate(prox_periodo = lead(Periodo, length(fatores_ordenados)),
         prox_estoque = lead(yend, length(fatores_ordenados)))

# save(dados_graf, file = "dados_exemplo.RData")


ano <- 2018
desloc <- 10

teste <- ggplot(dados_graf, aes(y = y, yend = yend, xend = Periodo)) +
  geom_point(aes(x = Periodo, y = ifelse(fatores == "Estoque_ant", yend, NA))) +
  #geom_label(aes(x = Periodo, y = ifelse(fatores == "Estoque_ant", yend-1e5, NA),
  #               label = paste0(
  #                 format(round(yend/1e6,2), big.mark = ".", decimal.mark = ","),
  #                 " bi")), 
  #           family = "Source Sans Pro", fill = "dimgrey", color = "white", size = 2) +
  geom_segment(aes(color = ifelse(fatores == "Estoque_ant", 
                                  "estoque", 
                                  as.character(fatores)),
                   x = if_else(fatores == "Resgates", Periodo + desloc, Periodo), # (1)
                   xend = if_else(fatores == "Resgates", Periodo + desloc, Periodo)), size = 2) +
  geom_segment(aes(x = Periodo + desloc, 
                   xend = prox_periodo, 
                   y = ifelse(fatores == "Estoque_ant", prox_estoque, NA),
                   yend = ifelse(fatores == "Estoque_ant", prox_estoque, NA)),
               linetype = "dotted") +
  geom_segment(aes(x = Periodo, 
                   xend = Periodo + desloc, 
                   y = ifelse(fatores == "Resgates", y, NA),
                   yend = ifelse(fatores == "Resgates", y, NA)),
               linetype = "dotted") +
  scale_color_manual(values = c("Juros" = "red", 
                                "Emissoes" = "firebrick",
                                "transf_positiva" = "lightcoral",
                                "transf_negativa" = "lightblue",
                                "Resgates" = "dodgerblue",
                                "estoque" = NA)) +
  scale_y_continuous(labels = function(x) {format(x/1e6, big.mark = ".", decimal.mark = ",")}) +
  labs(color = "Fator de Variação") +
  tema()

# (1) por algum motivo, o ifelse normal não funciona aqui. Dá um erro de tipo. Pesquisar um dia.

teste + theme(legend.position = "bottom", legend.text = element_text(size = 6))

# limpar base pro Lucas.

ggplotly(teste)

# teste plot_ly

# preparacao

fatores

sub_base <- function(criterio) {
  return(dados_graf %>% filter(fatores == criterio))
}

lista_fatores_plotly <- unique(dados_graf$fatores)

sub_bases <- purrr::map(lista_fatores_plotly, sub_base)
names(sub_bases) <- lista_fatores_plotly

formata <- function(x){
  paste0("R$", format(round(x/1e3, 2), big.mark = ".", decimal.mark = ","), " bi")
}

junta <- function(){
  paste(!!sym("fatores"), "<br />",
        !!sym("Periodo"), "<br />",
        (formata(!!sym("valor"))))
}

plot_ly() %>%
  add_segments(data = sub_bases[["Juros"]], 
               x = ~Periodo, xend = ~Periodo, y = ~y, yend = ~yend, name = "Juros") %>%
  add_segments(data = sub_bases[["Emissoes"]], text = ~paste(fatores, "<br />",
                                                             Periodo, "<br />",
                                                             formata(valor)), hoverinfo = "text",
               x = ~Periodo, xend = ~Periodo, y = ~y, yend = ~yend, name = "Emissões") %>%
  add_segments(data = sub_bases[["transf_positiva"]],
               x = ~Periodo, xend = ~Periodo, y = ~y, yend = ~yend, name = "Transferências(+)") %>%
  add_segments(data = sub_bases[["transf_negativa"]], 
               x = ~Periodo, xend = ~Periodo, y = ~y, yend = ~yend, name = "Transferências(-)") %>%
  add_segments(data = sub_bases[["Resgates"]], 
               x = ~Periodo+desloc, xend = ~Periodo+desloc, y = ~y, yend = ~yend, name = "Resgates") %>%
  add_segments(data = sub_bases[["Emissoes"]], 
               x = ~Periodo, xend = ~Periodo+desloc, y = ~yend, yend = ~yend,
               line = list(dash = "dot", width = 1), name = "") %>%
  add_segments(data = sub_bases[["Resgates"]], 
               x = ~Periodo+desloc, xend = ~prox_periodo, 
               y = ~yend, yend = ~yend, line = list(dash = "dot", width = 1), name = "") %>%
  add_markers(data = sub_bases[["Estoque_ant"]], 
              x = ~Periodo, y= ~valor, name = "Estoque")

```

